# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fetch_data', '0002_auto_20170301_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='newIntrusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ignore', models.BooleanField(default=False)),
                ('attempts', models.IntegerField()),
                ('morcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch_data.Morcha')),
            ],
        ),
    ]
