# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(editable=False, null=True)),
            ],
            options={
                'db_table': 'backup',
            },
        ),
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='Name of Battalion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
            ],
            options={
                'db_table': 'battalions',
            },
        ),
        migrations.CreateModel(
            name='Batterylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_datetime', models.DateTimeField()),
                ('battery_level', models.IntegerField()),
                ('charging', models.BooleanField()),
            ],
            options={
                'db_table': 'batterylogs',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('repr', models.CharField(default='', max_length=250, verbose_name='id of unit')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('req_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField()),
                ('packet_type', models.IntegerField()),
                ('source_addr', models.BigIntegerField()),
                ('dest_addr', models.BigIntegerField()),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Geospace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'geospaces',
            },
        ),
        migrations.CreateModel(
            name='Intrusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_datetime', models.DateTimeField()),
                ('verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('neutralized_datetime', models.DateTimeField(blank=True, null=True)),
                ('non_human_intrusion_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(editable=False)),
            ],
            options={
                'db_table': 'intrusions',
            },
        ),
        migrations.CreateModel(
            name='Morcha',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of morcha')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('repr', models.CharField(default='', max_length=250, verbose_name='id of qrt')),
                ('qrt_id', models.UUIDField(default=uuid.uuid4)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fetch_data.Geospace')),
            ],
            options={
                'db_table': 'morchas',
            },
        ),
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(editable=False, null=True)),
                ('morcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offlinemorcha', to='fetch_data.Morcha')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offlineunit', to='fetch_data.Device')),
            ],
            options={
                'db_table': 'offline',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of post')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('battalion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='fetch_data.Battalion')),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fetch_data.Geospace')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Weaksignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('morcha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weaksignalmorcha', to='fetch_data.Morcha')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weksignalunit', to='fetch_data.Device')),
            ],
            options={
                'db_table': 'weaksignal',
            },
        ),
        migrations.AddField(
            model_name='morcha',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morchas', to='fetch_data.Post'),
        ),
        migrations.AddField(
            model_name='intrusion',
            name='morcha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morcha', to='fetch_data.Morcha'),
        ),
        migrations.AddField(
            model_name='device',
            name='morcha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='fetch_data.Morcha'),
        ),
        migrations.AddField(
            model_name='batterylog',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batterylogdevice', to='fetch_data.Device'),
        ),
        migrations.AddField(
            model_name='batterylog',
            name='morcha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batterylogmorcha', to='fetch_data.Morcha'),
        ),
        migrations.AddField(
            model_name='battalion',
            name='geospace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fetch_data.Geospace'),
        ),
        migrations.AddField(
            model_name='backup',
            name='morcha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morchaevent', to='fetch_data.Morcha'),
        ),
        migrations.AddField(
            model_name='backup',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitevent', to='fetch_data.Device'),
        ),
    ]
