# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morcha',
            name='active',
        ),
        migrations.RemoveField(
            model_name='morcha',
            name='qrt_id',
        ),
        migrations.RemoveField(
            model_name='morcha',
            name='repr',
        ),
    ]
