# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_data', '0002_auto_20170301_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='repr',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('unit', 'unit')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='morcha',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='qrt_id'),
        ),
    ]
