# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_data', '0003_auto_20170302_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('unit', 'unit')], max_length=10),
        ),
    ]
